In [2]:
import pickle
import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split

data = pickle.load(open('motion_data.pickle', 'rb'))

X = data['X']
y = data['y']
actions = data['actions']

y = to_categorical(y)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=True
)

model = Sequential()
model.add(LSTM(64, return_sequences=True, input_shape=(30, 42)))
model.add(LSTM(64))
model.add(Dense(64, activation='relu'))
model.add(Dense(len(actions), activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=30)

model.save('motion_model.h5')

print("✅ Model trained and saved")

Epoch 1/30
8/8 [==============================] - 7s 21ms/step - loss: 1.5662 - accuracy: 0.3458
Epoch 2/30
8/8 [==============================] - 0s 20ms/step - loss: 1.3395 - accuracy: 0.4458
Epoch 3/30
8/8 [==============================] - 0s 18ms/step - loss: 0.9147 - accuracy: 0.5750
Epoch 4/30
8/8 [==============================] - 0s 20ms/step - loss: 0.5726 - accuracy: 0.8417
Epoch 5/30
8/8 [==============================] - 0s 22ms/step - loss: 0.3241 - accuracy: 0.9083
Epoch 6/30
8/8 [==============================] - 0s 24ms/step - loss: 0.3787 - accuracy: 0.9000
Epoch 7/30
8/8 [==============================] - 0s 21ms/step - loss: 0.4006 - accuracy: 0.8292
Epoch 8/30
8/8 [==============================] - 0s 20ms/step - loss: 0.3737 - accuracy: 0.8583
Epoch 9/30
8/8 [==============================] - 0s 19ms/step - loss: 0.1791 - accuracy: 0.9667
Epoch 10/30
8/8 [==============================] - 0s 19ms/step - loss: 0.1170 - accuracy: 0.9750
Epoch 11/30
8/8 [============

In [4]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
# 🔹 Evaluation
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true_classes = np.argmax(y_test, axis=1)

# 🔹 Accuracy
acc = accuracy_score(y_true_classes, y_pred_classes)
print(f"\n🎯 Accuracy: {acc * 100:.2f}%")

# 🔹 Classification Report
print("\n📊 Classification Report:")
print(classification_report(y_true_classes, y_pred_classes, target_names=actions))

# 🔹 Confusion Matrix
cm = confusion_matrix(y_true_classes, y_pred_classes)
print("\n📉 Confusion Matrix:")
print(cm)

2/2 [==============================] - 0s 9ms/step

🎯 Accuracy: 96.67%

📊 Classification Report:
              precision    recall  f1-score   support

       HELLO       1.00      1.00      1.00        17
          NO       0.93      0.93      0.93        14
          OK       1.00      0.90      0.95        10
      THANKS       1.00      1.00      1.00         6
         YES       0.93      1.00      0.96        13

    accuracy                           0.97        60
   macro avg       0.97      0.97      0.97        60
weighted avg       0.97      0.97      0.97        60


📉 Confusion Matrix:
[[17  0  0  0  0]
 [ 0 13  0  0  1]
 [ 0  1  9  0  0]
 [ 0  0  0  6  0]
 [ 0  0  0  0 13]]
